my_dbt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      user: sa
      password: WWIdbtdemo#1
      database: AdventureWorksDW2022
      schema: dbo
      trust_cert: true
      threads: 4